language: go
go:
- 1.x
os:
- linux
before_install:
# gox simplifies building for multiple architectures
- go get github.com/mitchellh/gox
install:
install:
- $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- cd ./cmd/webtythe/ui
- npm install
- cd -
env:
- GO111MODULE=on
script:
- cd ../
- git clone https://github.com/tythe-protocol/z_test1
- cd z_test1
- go build
- cd ../
- git clone https://github.com/tythe-protocol/z_test2
- cd z_test2
- go build
- cd ../
- git clone https://github.com/tythe-protocol/z_test3
- cd z_test3
- go build
- cd ../tythe
- go run ./cmd/webtythe/build.go
- gox -os="linux darwin windows" -arch="amd64" ./cmd/tythe
- go test -v -race ./...
- go vet ./...
deploy:
  overwrite: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZbLytk5NF70ximqrR1Lm5ZJkxm6Ag3LKlVxpOQPGZQwgF7Gyer9xAKkA1s/dVRTQVyzY9gthM4arC19PJcI576mZmevPtbzewJD9LU3imSdhxsIBpriIQQk2qs/+Ko8tjt7hzBAzp4/DlJ8+NBEgkIQICrgHAqE6Of37WtI/vQOF/Jr7yKenuDRsOFC/VfysA48o/2X4UpnE+FAHAA7gOlqtXcE/w5qo+eWf9j+tBgAZEubXRTNQUK05/V8GCTxM7IWShAimOlHQTaaH+2YIGGhPyudSw3uoYsUfd6KVKbzoND8ren6fQlhyE5u+cRy1PktYbpwA+gnHtxMhrkdnR6edXy9/IUtgOU5I/kdofnsYAe9i5VpDARJUIcpJHJm4YfK8xeF8OrLU/v+Gyv9H87/xgOL/Z670mSwjUbog+5S7ylZSBKi9GZfMZa+q+bv0iql3VXpnu32YSyyI6c+485dRnqm41nkxgpuvta4Mf94+nvSAppC+zoDFM0xzxHkAUO5tUgBTkP+209UQewMjbhZiifDlfhHjXXKs821AexsO1eXIm0pdEpIBezbvQ4+jv+8mnIBtesRjmOKCCM3CS6d0qOR0895QIGyYKKf81EsVW7dg0tT86DaJlUgCBSRQlCeKkNEJhNGVsxLQaHLGbHgDY4+VkRz14RwarblnmTA=
  file:
  - tythe_windows_amd64.exe
  - tythe_darwin_amd64
  - tythe_linux_amd64
  on:
    repo: tythe-protocol/tythe
    tags: true
  